baseURL = " http://lebonhenri/lebonhenri.github.io/"
languageCode = "en-au"
title = "Hugo Tutorial Getting Started"
# copyright overrides title for 
copyright = "Imagine by Riton Inc."
[markup.goldmark.renderer]
unsafe = true
[params]
# footer = "Footer override, can include **markdown**"
